options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: "ml-model-service"
  _REGION: "us-central1"
  _TAG: "$TAG_NAME"  # Tag Git que disparou o build

steps:
  # Etapa 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:${_TAG}'
      - '.'

  # Etapa 2: Push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:${_TAG}'

  # Etapa 3: Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:${_TAG}'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
