options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: "ml-model-service"
  _REGION: "us-central1"
  _TAG: "$TAG_NAME"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/$_SERVICE_NAME:${_TAG}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/$_SERVICE_NAME:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME',
      '--image',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ml-models/$_SERVICE_NAME:${_TAG}',
      '--region',
      '$_REGION',
      '--platform',
      'managed',
      '--allow-unauthenticated'
    ]

